// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/admin/v2alpha/clusters.proto

package envoy_admin_v2alpha

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import core "github.com/altipla-consulting/envoy-api/envoy/api/v2/core"
import _type "github.com/altipla-consulting/envoy-api/envoy/type"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Admin endpoint uses this wrapper for `/clusters` to display cluster status information.
// See :ref:`/clusters <operations_admin_interface_clusters>` for more information.
type Clusters struct {
	// Mapping from cluster name to each cluster's status.
	ClusterStatuses      []*ClusterStatus `protobuf:"bytes,1,rep,name=cluster_statuses,json=clusterStatuses,proto3" json:"cluster_statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Clusters) Reset()         { *m = Clusters{} }
func (m *Clusters) String() string { return proto.CompactTextString(m) }
func (*Clusters) ProtoMessage()    {}
func (*Clusters) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusters_6b5c57819826d337, []int{0}
}
func (m *Clusters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clusters.Unmarshal(m, b)
}
func (m *Clusters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clusters.Marshal(b, m, deterministic)
}
func (dst *Clusters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clusters.Merge(dst, src)
}
func (m *Clusters) XXX_Size() int {
	return xxx_messageInfo_Clusters.Size(m)
}
func (m *Clusters) XXX_DiscardUnknown() {
	xxx_messageInfo_Clusters.DiscardUnknown(m)
}

var xxx_messageInfo_Clusters proto.InternalMessageInfo

func (m *Clusters) GetClusterStatuses() []*ClusterStatus {
	if m != nil {
		return m.ClusterStatuses
	}
	return nil
}

// Details an individual cluster's current status.
type ClusterStatus struct {
	// Name of the cluster.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Denotes whether this cluster was added via API or configured statically.
	AddedViaApi bool `protobuf:"varint,2,opt,name=added_via_api,json=addedViaApi,proto3" json:"added_via_api,omitempty"`
	// The success rate threshold used in the last interval. The threshold is used to eject hosts
	// based on their success rate. See
	// :ref:`Cluster outlier detection <arch_overview_outlier_detection>` statistics
	//
	// Note: this field may be omitted in any of the three following cases:
	//
	// 1. There were not enough hosts with enough request volume to proceed with success rate based
	//    outlier ejection.
	// 2. The threshold is computed to be < 0 because a negative value implies that there was no
	//    threshold for that interval.
	// 3. Outlier detection is not enabled for this cluster.
	SuccessRateEjectionThreshold *_type.Percent `protobuf:"bytes,3,opt,name=success_rate_ejection_threshold,json=successRateEjectionThreshold,proto3" json:"success_rate_ejection_threshold,omitempty"`
	// Mapping from host address to the host's current status.
	HostStatuses         []*HostStatus `protobuf:"bytes,4,rep,name=host_statuses,json=hostStatuses,proto3" json:"host_statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ClusterStatus) Reset()         { *m = ClusterStatus{} }
func (m *ClusterStatus) String() string { return proto.CompactTextString(m) }
func (*ClusterStatus) ProtoMessage()    {}
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusters_6b5c57819826d337, []int{1}
}
func (m *ClusterStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterStatus.Unmarshal(m, b)
}
func (m *ClusterStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterStatus.Marshal(b, m, deterministic)
}
func (dst *ClusterStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterStatus.Merge(dst, src)
}
func (m *ClusterStatus) XXX_Size() int {
	return xxx_messageInfo_ClusterStatus.Size(m)
}
func (m *ClusterStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterStatus proto.InternalMessageInfo

func (m *ClusterStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterStatus) GetAddedViaApi() bool {
	if m != nil {
		return m.AddedViaApi
	}
	return false
}

func (m *ClusterStatus) GetSuccessRateEjectionThreshold() *_type.Percent {
	if m != nil {
		return m.SuccessRateEjectionThreshold
	}
	return nil
}

func (m *ClusterStatus) GetHostStatuses() []*HostStatus {
	if m != nil {
		return m.HostStatuses
	}
	return nil
}

// Current state of a particular host.
type HostStatus struct {
	// Address of this host.
	Address *core.Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// List of stats specific to this host.
	Stats []*SimpleMetric `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	// The host's current health status.
	HealthStatus *HostHealthStatus `protobuf:"bytes,3,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	// Request success rate for this host over the last calculated interval.
	//
	// Note: the message will not be present if host did not have enough request volume to calculate
	// success rate or the cluster did not have enough hosts to run through success rate outlier
	// ejection.
	SuccessRate *_type.Percent `protobuf:"bytes,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	// The host's weight. If not configured, the value defaults to 1.
	Weight               uint32   `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostStatus) Reset()         { *m = HostStatus{} }
func (m *HostStatus) String() string { return proto.CompactTextString(m) }
func (*HostStatus) ProtoMessage()    {}
func (*HostStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusters_6b5c57819826d337, []int{2}
}
func (m *HostStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostStatus.Unmarshal(m, b)
}
func (m *HostStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostStatus.Marshal(b, m, deterministic)
}
func (dst *HostStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostStatus.Merge(dst, src)
}
func (m *HostStatus) XXX_Size() int {
	return xxx_messageInfo_HostStatus.Size(m)
}
func (m *HostStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HostStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HostStatus proto.InternalMessageInfo

func (m *HostStatus) GetAddress() *core.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *HostStatus) GetStats() []*SimpleMetric {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *HostStatus) GetHealthStatus() *HostHealthStatus {
	if m != nil {
		return m.HealthStatus
	}
	return nil
}

func (m *HostStatus) GetSuccessRate() *_type.Percent {
	if m != nil {
		return m.SuccessRate
	}
	return nil
}

func (m *HostStatus) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

// Health status for a host.
type HostHealthStatus struct {
	// The host is currently failing active health checks.
	FailedActiveHealthCheck bool `protobuf:"varint,1,opt,name=failed_active_health_check,json=failedActiveHealthCheck,proto3" json:"failed_active_health_check,omitempty"`
	// The host is currently considered an outlier and has been ejected.
	FailedOutlierCheck bool `protobuf:"varint,2,opt,name=failed_outlier_check,json=failedOutlierCheck,proto3" json:"failed_outlier_check,omitempty"`
	// Health status as reported by EDS. Note: only HEALTHY and UNHEALTHY are currently supported
	// here.
	// TODO(mrice32): pipe through remaining EDS health status possibilities.
	EdsHealthStatus      core.HealthStatus `protobuf:"varint,3,opt,name=eds_health_status,json=edsHealthStatus,proto3,enum=envoy.api.v2.core.HealthStatus" json:"eds_health_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HostHealthStatus) Reset()         { *m = HostHealthStatus{} }
func (m *HostHealthStatus) String() string { return proto.CompactTextString(m) }
func (*HostHealthStatus) ProtoMessage()    {}
func (*HostHealthStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_clusters_6b5c57819826d337, []int{3}
}
func (m *HostHealthStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostHealthStatus.Unmarshal(m, b)
}
func (m *HostHealthStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostHealthStatus.Marshal(b, m, deterministic)
}
func (dst *HostHealthStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostHealthStatus.Merge(dst, src)
}
func (m *HostHealthStatus) XXX_Size() int {
	return xxx_messageInfo_HostHealthStatus.Size(m)
}
func (m *HostHealthStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HostHealthStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HostHealthStatus proto.InternalMessageInfo

func (m *HostHealthStatus) GetFailedActiveHealthCheck() bool {
	if m != nil {
		return m.FailedActiveHealthCheck
	}
	return false
}

func (m *HostHealthStatus) GetFailedOutlierCheck() bool {
	if m != nil {
		return m.FailedOutlierCheck
	}
	return false
}

func (m *HostHealthStatus) GetEdsHealthStatus() core.HealthStatus {
	if m != nil {
		return m.EdsHealthStatus
	}
	return core.HealthStatus_UNKNOWN
}

func init() {
	proto.RegisterType((*Clusters)(nil), "envoy.admin.v2alpha.Clusters")
	proto.RegisterType((*ClusterStatus)(nil), "envoy.admin.v2alpha.ClusterStatus")
	proto.RegisterType((*HostStatus)(nil), "envoy.admin.v2alpha.HostStatus")
	proto.RegisterType((*HostHealthStatus)(nil), "envoy.admin.v2alpha.HostHealthStatus")
}

func init() {
	proto.RegisterFile("envoy/admin/v2alpha/clusters.proto", fileDescriptor_clusters_6b5c57819826d337)
}

var fileDescriptor_clusters_6b5c57819826d337 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0xae, 0x1b, 0xe5, 0x64, 0x61, 0xc3, 0x43, 0x10, 0x55, 0x48, 0xcd, 0x22, 0x90,
	0x72, 0x95, 0xa0, 0x80, 0xe0, 0x82, 0xab, 0x6a, 0x20, 0x4d, 0xa0, 0x09, 0x94, 0x21, 0x24, 0xb8,
	0xb1, 0x8c, 0x7d, 0x20, 0x86, 0x34, 0x89, 0x62, 0x37, 0x68, 0x4f, 0xc2, 0x5b, 0xf1, 0x1e, 0xbc,
	0x05, 0xaa, 0xed, 0xae, 0xd9, 0xd6, 0xdd, 0xc5, 0x39, 0xdf, 0xdf, 0xfe, 0xff, 0x7f, 0x1c, 0x88,
	0xb1, 0xee, 0x9b, 0x8b, 0x8c, 0x89, 0x85, 0xac, 0xb3, 0x3e, 0x67, 0x55, 0x5b, 0xb2, 0x8c, 0x57,
	0x4b, 0xa5, 0xb1, 0x53, 0x69, 0xdb, 0x35, 0xba, 0x21, 0x47, 0x86, 0x49, 0x0d, 0x93, 0x3a, 0x66,
	0x7a, 0xbc, 0x4d, 0xb8, 0x40, 0xdd, 0x49, 0xee, 0x74, 0xd3, 0x99, 0x43, 0x5a, 0x99, 0xf5, 0x79,
	0xc6, 0x9b, 0x0e, 0x33, 0x26, 0x44, 0x87, 0x6a, 0x0d, 0x3c, 0xb9, 0x09, 0x94, 0xc8, 0x2a, 0x5d,
	0x52, 0x5e, 0x22, 0xff, 0xe5, 0xa8, 0xd0, 0x52, 0xfa, 0xa2, 0xc5, 0xac, 0xc5, 0x8e, 0x63, 0xad,
	0xed, 0x24, 0xfe, 0x02, 0x93, 0x13, 0x67, 0x95, 0x9c, 0xc1, 0xa1, 0xb3, 0x4d, 0x95, 0x66, 0x7a,
	0xa9, 0x50, 0x85, 0x5e, 0xb4, 0x93, 0xf8, 0x79, 0x9c, 0x6e, 0xf1, 0x9f, 0x3a, 0xe1, 0xb9, 0x61,
	0x8b, 0x03, 0x3e, 0x3c, 0xa2, 0x8a, 0xff, 0x79, 0x10, 0x5c, 0x41, 0x08, 0x81, 0x71, 0xcd, 0x16,
	0x18, 0x7a, 0x91, 0x97, 0xdc, 0x2d, 0xcc, 0x33, 0x89, 0x21, 0x60, 0x42, 0xa0, 0xa0, 0xbd, 0x64,
	0x94, 0xb5, 0x32, 0x1c, 0x45, 0x5e, 0x32, 0x29, 0x7c, 0xf3, 0xf2, 0xb3, 0x64, 0xf3, 0x56, 0x92,
	0xaf, 0x30, 0x53, 0x4b, 0xce, 0x51, 0x29, 0xda, 0x31, 0x8d, 0x14, 0x7f, 0x22, 0xd7, 0xb2, 0xa9,
	0xa9, 0x2e, 0x3b, 0x54, 0x65, 0x53, 0x89, 0x70, 0x27, 0xf2, 0x12, 0x3f, 0x3f, 0x72, 0x3e, 0x57,
	0x41, 0xd3, 0x8f, 0x36, 0x68, 0xf1, 0xd8, 0x69, 0x0b, 0xa6, 0xf1, 0xad, 0x53, 0x7e, 0x5a, 0x0b,
	0xc9, 0x1b, 0x08, 0xca, 0x46, 0xe9, 0x4d, 0xe2, 0xb1, 0x49, 0x3c, 0xdb, 0x9a, 0xf8, 0xb4, 0x51,
	0xda, 0xc5, 0xdd, 0x2f, 0x2f, 0x9f, 0x51, 0xc5, 0x7f, 0x46, 0x00, 0x9b, 0x21, 0x79, 0x01, 0x77,
	0xdc, 0x9a, 0x4c, 0x56, 0x3f, 0x9f, 0xae, 0x7f, 0xae, 0x95, 0x69, 0x9f, 0xa7, 0xab, 0x3d, 0xa5,
	0x73, 0x4b, 0x14, 0x6b, 0x94, 0xbc, 0x82, 0xdd, 0x95, 0x0b, 0x15, 0x8e, 0x8c, 0x85, 0xe3, 0xad,
	0x16, 0xce, 0xe5, 0xa2, 0xad, 0xf0, 0xcc, 0xdc, 0x92, 0xc2, 0xf2, 0xe4, 0x1d, 0x04, 0x6e, 0xe9,
	0x36, 0x85, 0x6b, 0xe3, 0xe9, 0xad, 0x19, 0x4e, 0x0d, 0x7d, 0x99, 0x64, 0x70, 0x22, 0x2f, 0x61,
	0x7f, 0xd8, 0x75, 0x38, 0xbe, 0xbd, 0x58, 0x7f, 0x50, 0x2c, 0x79, 0x08, 0x7b, 0xbf, 0x51, 0xfe,
	0x28, 0x75, 0xb8, 0x1b, 0x79, 0x49, 0x50, 0xb8, 0x53, 0xfc, 0xd7, 0x83, 0xc3, 0xeb, 0x7f, 0x49,
	0x5e, 0xc3, 0xf4, 0x3b, 0x93, 0x15, 0x0a, 0xca, 0xb8, 0x96, 0x3d, 0xd2, 0xe1, 0x9d, 0x35, 0x95,
	0x4d, 0x8a, 0x47, 0x96, 0x98, 0x1b, 0xc0, 0xaa, 0x4f, 0x56, 0x63, 0xf2, 0x0c, 0x1e, 0x38, 0x71,
	0xb3, 0xd4, 0x95, 0xc4, 0xce, 0xc9, 0xec, 0xc5, 0x21, 0x76, 0xf6, 0xc1, 0x8e, 0xac, 0xe2, 0x3d,
	0xdc, 0x47, 0xa1, 0xe8, 0xcd, 0x8e, 0xee, 0x6d, 0xf6, 0x3c, 0x58, 0xcc, 0x95, 0x76, 0x0e, 0x50,
	0xa8, 0xe1, 0x8b, 0x6f, 0x7b, 0xe6, 0xc3, 0x79, 0xfe, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x78, 0xee,
	0x5e, 0x5a, 0xf7, 0x03, 0x00, 0x00,
}
