// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/core/grpc_service.proto

package core

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// gRPC service configuration. This is used by :ref:`ApiConfigSource
// <envoy_api_msg_core.ApiConfigSource>` and filter configurations.
type GrpcService struct {
	// Types that are valid to be assigned to TargetSpecifier:
	//	*GrpcService_EnvoyGrpc_
	//	*GrpcService_GoogleGrpc_
	TargetSpecifier isGrpcService_TargetSpecifier `protobuf_oneof:"target_specifier"`
	// The timeout for the gRPC request. This is the timeout for a specific
	// request.
	Timeout *types.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Additional metadata to include in streams initiated to the GrpcService.
	// This can be used for scenarios in which additional ad hoc authorization
	// headers (e.g. `x-foo-bar: baz-key`) are to be injected.
	InitialMetadata      []*HeaderValue `protobuf:"bytes,5,rep,name=initial_metadata,json=initialMetadata,proto3" json:"initial_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GrpcService) Reset()         { *m = GrpcService{} }
func (m *GrpcService) String() string { return proto.CompactTextString(m) }
func (*GrpcService) ProtoMessage()    {}
func (*GrpcService) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0}
}

func (m *GrpcService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService.Unmarshal(m, b)
}
func (m *GrpcService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService.Marshal(b, m, deterministic)
}
func (m *GrpcService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService.Merge(m, src)
}
func (m *GrpcService) XXX_Size() int {
	return xxx_messageInfo_GrpcService.Size(m)
}
func (m *GrpcService) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService proto.InternalMessageInfo

type isGrpcService_TargetSpecifier interface {
	isGrpcService_TargetSpecifier()
}

type GrpcService_EnvoyGrpc_ struct {
	EnvoyGrpc *GrpcService_EnvoyGrpc `protobuf:"bytes,1,opt,name=envoy_grpc,json=envoyGrpc,proto3,oneof"`
}

type GrpcService_GoogleGrpc_ struct {
	GoogleGrpc *GrpcService_GoogleGrpc `protobuf:"bytes,2,opt,name=google_grpc,json=googleGrpc,proto3,oneof"`
}

func (*GrpcService_EnvoyGrpc_) isGrpcService_TargetSpecifier() {}

func (*GrpcService_GoogleGrpc_) isGrpcService_TargetSpecifier() {}

func (m *GrpcService) GetTargetSpecifier() isGrpcService_TargetSpecifier {
	if m != nil {
		return m.TargetSpecifier
	}
	return nil
}

func (m *GrpcService) GetEnvoyGrpc() *GrpcService_EnvoyGrpc {
	if x, ok := m.GetTargetSpecifier().(*GrpcService_EnvoyGrpc_); ok {
		return x.EnvoyGrpc
	}
	return nil
}

func (m *GrpcService) GetGoogleGrpc() *GrpcService_GoogleGrpc {
	if x, ok := m.GetTargetSpecifier().(*GrpcService_GoogleGrpc_); ok {
		return x.GoogleGrpc
	}
	return nil
}

func (m *GrpcService) GetTimeout() *types.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *GrpcService) GetInitialMetadata() []*HeaderValue {
	if m != nil {
		return m.InitialMetadata
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GrpcService) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GrpcService_EnvoyGrpc_)(nil),
		(*GrpcService_GoogleGrpc_)(nil),
	}
}

type GrpcService_EnvoyGrpc struct {
	// The name of the upstream gRPC cluster. SSL credentials will be supplied
	// in the :ref:`Cluster <envoy_api_msg_Cluster>` :ref:`tls_context
	// <envoy_api_field_Cluster.tls_context>`.
	ClusterName          string   `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcService_EnvoyGrpc) Reset()         { *m = GrpcService_EnvoyGrpc{} }
func (m *GrpcService_EnvoyGrpc) String() string { return proto.CompactTextString(m) }
func (*GrpcService_EnvoyGrpc) ProtoMessage()    {}
func (*GrpcService_EnvoyGrpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 0}
}

func (m *GrpcService_EnvoyGrpc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_EnvoyGrpc.Unmarshal(m, b)
}
func (m *GrpcService_EnvoyGrpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_EnvoyGrpc.Marshal(b, m, deterministic)
}
func (m *GrpcService_EnvoyGrpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_EnvoyGrpc.Merge(m, src)
}
func (m *GrpcService_EnvoyGrpc) XXX_Size() int {
	return xxx_messageInfo_GrpcService_EnvoyGrpc.Size(m)
}
func (m *GrpcService_EnvoyGrpc) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_EnvoyGrpc.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_EnvoyGrpc proto.InternalMessageInfo

func (m *GrpcService_EnvoyGrpc) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

// [#proto-status: draft]
type GrpcService_GoogleGrpc struct {
	// The target URI when using the `Google C++ gRPC client
	// <https://github.com/grpc/grpc>`_. SSL credentials will be supplied in
	// :ref:`channel_credentials <envoy_api_field_core.GrpcService.GoogleGrpc.channel_credentials>`.
	TargetUri          string                                     `protobuf:"bytes,1,opt,name=target_uri,json=targetUri,proto3" json:"target_uri,omitempty"`
	ChannelCredentials *GrpcService_GoogleGrpc_ChannelCredentials `protobuf:"bytes,2,opt,name=channel_credentials,json=channelCredentials,proto3" json:"channel_credentials,omitempty"`
	// A set of call credentials that can be composed with `channel credentials
	// <https://grpc.io/docs/guides/auth.html#credential-types>`_.
	CallCredentials []*GrpcService_GoogleGrpc_CallCredentials `protobuf:"bytes,3,rep,name=call_credentials,json=callCredentials,proto3" json:"call_credentials,omitempty"`
	// The human readable prefix to use when emitting statistics for the gRPC
	// service.
	//
	// .. csv-table::
	//    :header: Name, Type, Description
	//    :widths: 1, 1, 2
	//
	//    streams_total, Counter, Total number of streams opened
	//    streams_closed_<gRPC status code>, Counter, Total streams closed with <gRPC status code>
	StatPrefix string `protobuf:"bytes,4,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	// The name of the Google gRPC credentials factory to use. This must have been registered with
	// Envoy. If this is empty, a default credentials factory will be used that sets up channel
	// credentials based on other configuration parameters.
	CredentialsFactoryName string `protobuf:"bytes,5,opt,name=credentials_factory_name,json=credentialsFactoryName,proto3" json:"credentials_factory_name,omitempty"`
	// Additional configuration for site-specific customizations of the Google
	// gRPC library.
	Config               *types.Struct `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GrpcService_GoogleGrpc) Reset()         { *m = GrpcService_GoogleGrpc{} }
func (m *GrpcService_GoogleGrpc) String() string { return proto.CompactTextString(m) }
func (*GrpcService_GoogleGrpc) ProtoMessage()    {}
func (*GrpcService_GoogleGrpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1}
}

func (m *GrpcService_GoogleGrpc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc.Size(m)
}
func (m *GrpcService_GoogleGrpc) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc proto.InternalMessageInfo

func (m *GrpcService_GoogleGrpc) GetTargetUri() string {
	if m != nil {
		return m.TargetUri
	}
	return ""
}

func (m *GrpcService_GoogleGrpc) GetChannelCredentials() *GrpcService_GoogleGrpc_ChannelCredentials {
	if m != nil {
		return m.ChannelCredentials
	}
	return nil
}

func (m *GrpcService_GoogleGrpc) GetCallCredentials() []*GrpcService_GoogleGrpc_CallCredentials {
	if m != nil {
		return m.CallCredentials
	}
	return nil
}

func (m *GrpcService_GoogleGrpc) GetStatPrefix() string {
	if m != nil {
		return m.StatPrefix
	}
	return ""
}

func (m *GrpcService_GoogleGrpc) GetCredentialsFactoryName() string {
	if m != nil {
		return m.CredentialsFactoryName
	}
	return ""
}

func (m *GrpcService_GoogleGrpc) GetConfig() *types.Struct {
	if m != nil {
		return m.Config
	}
	return nil
}

// See https://grpc.io/grpc/cpp/structgrpc_1_1_ssl_credentials_options.html.
type GrpcService_GoogleGrpc_SslCredentials struct {
	// PEM encoded server root certificates.
	RootCerts *DataSource `protobuf:"bytes,1,opt,name=root_certs,json=rootCerts,proto3" json:"root_certs,omitempty"`
	// PEM encoded client private key.
	PrivateKey *DataSource `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// PEM encoded client certificate chain.
	CertChain            *DataSource `protobuf:"bytes,3,opt,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GrpcService_GoogleGrpc_SslCredentials) Reset()         { *m = GrpcService_GoogleGrpc_SslCredentials{} }
func (m *GrpcService_GoogleGrpc_SslCredentials) String() string { return proto.CompactTextString(m) }
func (*GrpcService_GoogleGrpc_SslCredentials) ProtoMessage()    {}
func (*GrpcService_GoogleGrpc_SslCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 0}
}

func (m *GrpcService_GoogleGrpc_SslCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_SslCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_SslCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_SslCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_SslCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_SslCredentials proto.InternalMessageInfo

func (m *GrpcService_GoogleGrpc_SslCredentials) GetRootCerts() *DataSource {
	if m != nil {
		return m.RootCerts
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_SslCredentials) GetPrivateKey() *DataSource {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_SslCredentials) GetCertChain() *DataSource {
	if m != nil {
		return m.CertChain
	}
	return nil
}

// Local channel credentials. Only UDS is supported for now.
// See https://github.com/grpc/grpc/pull/15909.
type GrpcService_GoogleGrpc_GoogleLocalCredentials struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) Reset() {
	*m = GrpcService_GoogleGrpc_GoogleLocalCredentials{}
}
func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) String() string {
	return proto.CompactTextString(m)
}
func (*GrpcService_GoogleGrpc_GoogleLocalCredentials) ProtoMessage() {}
func (*GrpcService_GoogleGrpc_GoogleLocalCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 1}
}

func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_GoogleLocalCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_GoogleLocalCredentials proto.InternalMessageInfo

// See https://grpc.io/docs/guides/auth.html#credential-types to understand Channel and Call
// credential types.
type GrpcService_GoogleGrpc_ChannelCredentials struct {
	// Types that are valid to be assigned to CredentialSpecifier:
	//	*GrpcService_GoogleGrpc_ChannelCredentials_SslCredentials
	//	*GrpcService_GoogleGrpc_ChannelCredentials_GoogleDefault
	//	*GrpcService_GoogleGrpc_ChannelCredentials_LocalCredentials
	CredentialSpecifier  isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier `protobuf_oneof:"credential_specifier"`
	XXX_NoUnkeyedLiteral struct{}                                                        `json:"-"`
	XXX_unrecognized     []byte                                                          `json:"-"`
	XXX_sizecache        int32                                                           `json:"-"`
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) Reset() {
	*m = GrpcService_GoogleGrpc_ChannelCredentials{}
}
func (m *GrpcService_GoogleGrpc_ChannelCredentials) String() string { return proto.CompactTextString(m) }
func (*GrpcService_GoogleGrpc_ChannelCredentials) ProtoMessage()    {}
func (*GrpcService_GoogleGrpc_ChannelCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 2}
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_ChannelCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_ChannelCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_ChannelCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_ChannelCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_ChannelCredentials proto.InternalMessageInfo

type isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier interface {
	isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier()
}

type GrpcService_GoogleGrpc_ChannelCredentials_SslCredentials struct {
	SslCredentials *GrpcService_GoogleGrpc_SslCredentials `protobuf:"bytes,1,opt,name=ssl_credentials,json=sslCredentials,proto3,oneof"`
}

type GrpcService_GoogleGrpc_ChannelCredentials_GoogleDefault struct {
	GoogleDefault *types.Empty `protobuf:"bytes,2,opt,name=google_default,json=googleDefault,proto3,oneof"`
}

type GrpcService_GoogleGrpc_ChannelCredentials_LocalCredentials struct {
	LocalCredentials *GrpcService_GoogleGrpc_GoogleLocalCredentials `protobuf:"bytes,3,opt,name=local_credentials,json=localCredentials,proto3,oneof"`
}

func (*GrpcService_GoogleGrpc_ChannelCredentials_SslCredentials) isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_ChannelCredentials_GoogleDefault) isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_ChannelCredentials_LocalCredentials) isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier() {
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) GetCredentialSpecifier() isGrpcService_GoogleGrpc_ChannelCredentials_CredentialSpecifier {
	if m != nil {
		return m.CredentialSpecifier
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) GetSslCredentials() *GrpcService_GoogleGrpc_SslCredentials {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_ChannelCredentials_SslCredentials); ok {
		return x.SslCredentials
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) GetGoogleDefault() *types.Empty {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_ChannelCredentials_GoogleDefault); ok {
		return x.GoogleDefault
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_ChannelCredentials) GetLocalCredentials() *GrpcService_GoogleGrpc_GoogleLocalCredentials {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_ChannelCredentials_LocalCredentials); ok {
		return x.LocalCredentials
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GrpcService_GoogleGrpc_ChannelCredentials) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GrpcService_GoogleGrpc_ChannelCredentials_SslCredentials)(nil),
		(*GrpcService_GoogleGrpc_ChannelCredentials_GoogleDefault)(nil),
		(*GrpcService_GoogleGrpc_ChannelCredentials_LocalCredentials)(nil),
	}
}

type GrpcService_GoogleGrpc_CallCredentials struct {
	// Types that are valid to be assigned to CredentialSpecifier:
	//	*GrpcService_GoogleGrpc_CallCredentials_AccessToken
	//	*GrpcService_GoogleGrpc_CallCredentials_GoogleComputeEngine
	//	*GrpcService_GoogleGrpc_CallCredentials_GoogleRefreshToken
	//	*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJwtAccess
	//	*GrpcService_GoogleGrpc_CallCredentials_GoogleIam
	//	*GrpcService_GoogleGrpc_CallCredentials_FromPlugin
	CredentialSpecifier  isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier `protobuf_oneof:"credential_specifier"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *GrpcService_GoogleGrpc_CallCredentials) Reset() {
	*m = GrpcService_GoogleGrpc_CallCredentials{}
}
func (m *GrpcService_GoogleGrpc_CallCredentials) String() string { return proto.CompactTextString(m) }
func (*GrpcService_GoogleGrpc_CallCredentials) ProtoMessage()    {}
func (*GrpcService_GoogleGrpc_CallCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 3}
}

func (m *GrpcService_GoogleGrpc_CallCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_CallCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_CallCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_CallCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_CallCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials proto.InternalMessageInfo

type isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier interface {
	isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier()
}

type GrpcService_GoogleGrpc_CallCredentials_AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_GoogleComputeEngine struct {
	GoogleComputeEngine *types.Empty `protobuf:"bytes,2,opt,name=google_compute_engine,json=googleComputeEngine,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_GoogleRefreshToken struct {
	GoogleRefreshToken string `protobuf:"bytes,3,opt,name=google_refresh_token,json=googleRefreshToken,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJwtAccess struct {
	ServiceAccountJwtAccess *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials `protobuf:"bytes,4,opt,name=service_account_jwt_access,json=serviceAccountJwtAccess,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_GoogleIam struct {
	GoogleIam *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials `protobuf:"bytes,5,opt,name=google_iam,json=googleIam,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_FromPlugin struct {
	FromPlugin *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin `protobuf:"bytes,6,opt,name=from_plugin,json=fromPlugin,proto3,oneof"`
}

func (*GrpcService_GoogleGrpc_CallCredentials_AccessToken) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_GoogleComputeEngine) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_GoogleRefreshToken) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJwtAccess) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_GoogleIam) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_FromPlugin) isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier() {
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetCredentialSpecifier() isGrpcService_GoogleGrpc_CallCredentials_CredentialSpecifier {
	if m != nil {
		return m.CredentialSpecifier
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetAccessToken() string {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_AccessToken); ok {
		return x.AccessToken
	}
	return ""
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetGoogleComputeEngine() *types.Empty {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_GoogleComputeEngine); ok {
		return x.GoogleComputeEngine
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetGoogleRefreshToken() string {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_GoogleRefreshToken); ok {
		return x.GoogleRefreshToken
	}
	return ""
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetServiceAccountJwtAccess() *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJwtAccess); ok {
		return x.ServiceAccountJwtAccess
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetGoogleIam() *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_GoogleIam); ok {
		return x.GoogleIam
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials) GetFromPlugin() *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin {
	if x, ok := m.GetCredentialSpecifier().(*GrpcService_GoogleGrpc_CallCredentials_FromPlugin); ok {
		return x.FromPlugin
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GrpcService_GoogleGrpc_CallCredentials) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GrpcService_GoogleGrpc_CallCredentials_AccessToken)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_GoogleComputeEngine)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_GoogleRefreshToken)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJwtAccess)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_GoogleIam)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_FromPlugin)(nil),
	}
}

type GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials struct {
	JsonKey              string   `protobuf:"bytes,1,opt,name=json_key,json=jsonKey,proto3" json:"json_key,omitempty"`
	TokenLifetimeSeconds uint64   `protobuf:"varint,2,opt,name=token_lifetime_seconds,json=tokenLifetimeSeconds,proto3" json:"token_lifetime_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) Reset() {
	*m = GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials{}
}
func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) String() string {
	return proto.CompactTextString(m)
}
func (*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) ProtoMessage() {}
func (*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 3, 0}
}

func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials proto.InternalMessageInfo

func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) GetJsonKey() string {
	if m != nil {
		return m.JsonKey
	}
	return ""
}

func (m *GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials) GetTokenLifetimeSeconds() uint64 {
	if m != nil {
		return m.TokenLifetimeSeconds
	}
	return 0
}

type GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials struct {
	AuthorizationToken   string   `protobuf:"bytes,1,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorization_token,omitempty"`
	AuthoritySelector    string   `protobuf:"bytes,2,opt,name=authority_selector,json=authoritySelector,proto3" json:"authority_selector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) Reset() {
	*m = GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials{}
}
func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) String() string {
	return proto.CompactTextString(m)
}
func (*GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) ProtoMessage() {}
func (*GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 3, 1}
}

func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials.Size(m)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials proto.InternalMessageInfo

func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) GetAuthorizationToken() string {
	if m != nil {
		return m.AuthorizationToken
	}
	return ""
}

func (m *GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials) GetAuthoritySelector() string {
	if m != nil {
		return m.AuthoritySelector
	}
	return ""
}

type GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to ConfigType:
	//	*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_Config
	//	*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_TypedConfig
	ConfigType           isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType `protobuf_oneof:"config_type"`
	XXX_NoUnkeyedLiteral struct{}                                                                          `json:"-"`
	XXX_unrecognized     []byte                                                                            `json:"-"`
	XXX_sizecache        int32                                                                             `json:"-"`
}

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) Reset() {
	*m = GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin{}
}
func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) String() string {
	return proto.CompactTextString(m)
}
func (*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) ProtoMessage() {}
func (*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_936cbcb9830ffdc2, []int{0, 1, 3, 2}
}

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin.Unmarshal(m, b)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin.Marshal(b, m, deterministic)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin.Merge(m, src)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_Size() int {
	return xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin.Size(m)
}
func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin proto.InternalMessageInfo

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType interface {
	isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType()
}

type GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_Config struct {
	Config *types.Struct `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

type GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_TypedConfig struct {
	TypedConfig *types.Any `protobuf:"bytes,3,opt,name=typed_config,json=typedConfig,proto3,oneof"`
}

func (*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_Config) isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType() {
}

func (*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_TypedConfig) isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType() {
}

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) GetConfigType() isGrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_ConfigType {
	if m != nil {
		return m.ConfigType
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) GetConfig() *types.Struct {
	if x, ok := m.GetConfigType().(*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_Config); ok {
		return x.Config
	}
	return nil
}

func (m *GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) GetTypedConfig() *types.Any {
	if x, ok := m.GetConfigType().(*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_TypedConfig); ok {
		return x.TypedConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_Config)(nil),
		(*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin_TypedConfig)(nil),
	}
}

func init() {
	proto.RegisterType((*GrpcService)(nil), "envoy.api.v2.core.GrpcService")
	proto.RegisterType((*GrpcService_EnvoyGrpc)(nil), "envoy.api.v2.core.GrpcService.EnvoyGrpc")
	proto.RegisterType((*GrpcService_GoogleGrpc)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc")
	proto.RegisterType((*GrpcService_GoogleGrpc_SslCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.SslCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_GoogleLocalCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.GoogleLocalCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_ChannelCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.ChannelCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_CallCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_CallCredentials_ServiceAccountJWTAccessCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.ServiceAccountJWTAccessCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_CallCredentials_GoogleIAMCredentials)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.GoogleIAMCredentials")
	proto.RegisterType((*GrpcService_GoogleGrpc_CallCredentials_MetadataCredentialsFromPlugin)(nil), "envoy.api.v2.core.GrpcService.GoogleGrpc.CallCredentials.MetadataCredentialsFromPlugin")
}

func init() {
	proto.RegisterFile("envoy/api/v2/core/grpc_service.proto", fileDescriptor_936cbcb9830ffdc2)
}

var fileDescriptor_936cbcb9830ffdc2 = []byte{
	// 1062 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x4e, 0x1b, 0xc7,
	0x17, 0xb6, 0xc1, 0x01, 0x7c, 0x96, 0x80, 0x19, 0xfc, 0x03, 0xb3, 0x49, 0xf8, 0xa1, 0xb4, 0xaa,
	0x68, 0xa5, 0xae, 0x55, 0xa7, 0x52, 0x83, 0x14, 0xb5, 0xc5, 0x86, 0xc4, 0xa4, 0x24, 0x42, 0xeb,
	0xb4, 0xb9, 0xa9, 0x34, 0x1a, 0xc6, 0x63, 0x33, 0xc9, 0x7a, 0x67, 0x35, 0x3b, 0xeb, 0xc4, 0xb9,
	0xec, 0x6b, 0xf4, 0x05, 0x7a, 0xd9, 0xc7, 0xe8, 0x45, 0xef, 0xdb, 0xeb, 0x3e, 0x45, 0xd5, 0xab,
	0x6a, 0xfe, 0x18, 0xbc, 0x36, 0x02, 0xca, 0xdd, 0xee, 0xf9, 0xce, 0x77, 0xfe, 0x7c, 0x73, 0xe6,
	0x0c, 0x7c, 0xcc, 0xe2, 0xa1, 0x18, 0xd5, 0x49, 0xc2, 0xeb, 0xc3, 0x46, 0x9d, 0x0a, 0xc9, 0xea,
	0x7d, 0x99, 0x50, 0x9c, 0x32, 0x39, 0xe4, 0x94, 0x05, 0x89, 0x14, 0x4a, 0xa0, 0x35, 0xe3, 0x15,
	0x90, 0x84, 0x07, 0xc3, 0x46, 0xa0, 0xbd, 0xfc, 0xfb, 0xb3, 0xc4, 0x53, 0x92, 0x3a, 0x82, 0xbf,
	0xd5, 0x17, 0xa2, 0x1f, 0xb1, 0xba, 0xf9, 0x3b, 0xcd, 0x7a, 0x75, 0x12, 0x8f, 0x1c, 0xb4, 0x3d,
	0x0d, 0x75, 0x33, 0x49, 0x14, 0x17, 0xb1, 0xc3, 0xef, 0x4f, 0xe3, 0xa9, 0x92, 0x19, 0x55, 0x0e,
	0xbd, 0x37, 0x8d, 0xb2, 0x41, 0xa2, 0xc6, 0xa1, 0x37, 0x87, 0x24, 0xe2, 0x5d, 0xa2, 0x58, 0x7d,
	0xfc, 0xe1, 0x80, 0x6a, 0x5f, 0xf4, 0x85, 0xf9, 0xac, 0xeb, 0x2f, 0x6b, 0x7d, 0xf8, 0x27, 0x02,
	0xef, 0x99, 0x4c, 0x68, 0xc7, 0xf6, 0x8a, 0x8e, 0x00, 0x4c, 0x53, 0x58, 0x2b, 0x50, 0x2b, 0xee,
	0x14, 0x77, 0xbd, 0xc6, 0x6e, 0x30, 0xd3, 0x7a, 0x30, 0xc1, 0x09, 0x0e, 0x35, 0xaa, 0x0d, 0xed,
	0x42, 0x58, 0x66, 0xe3, 0x1f, 0x74, 0x0c, 0x9e, 0x2d, 0xd4, 0xc6, 0x9a, 0x33, 0xb1, 0x3e, 0xbd,
	0x26, 0xd6, 0x33, 0xc3, 0x70, 0xc1, 0xa0, 0x7f, 0xfe, 0x87, 0x1e, 0xc1, 0xa2, 0xe2, 0x03, 0x26,
	0x32, 0x55, 0x9b, 0x37, 0x91, 0xb6, 0x02, 0x8b, 0x06, 0x63, 0x19, 0x82, 0x03, 0x27, 0x62, 0x38,
	0xf6, 0x44, 0x47, 0x50, 0xe1, 0x31, 0x57, 0x9c, 0x44, 0x78, 0xc0, 0x14, 0xe9, 0x12, 0x45, 0x6a,
	0x77, 0x76, 0xe6, 0x77, 0xbd, 0xc6, 0xf6, 0x25, 0x75, 0xb4, 0x19, 0xe9, 0x32, 0xf9, 0x03, 0x89,
	0x32, 0x16, 0xae, 0x3a, 0xde, 0x0b, 0x47, 0xf3, 0xbf, 0x82, 0xf2, 0x79, 0x9f, 0xe8, 0x33, 0x58,
	0xa6, 0x51, 0x96, 0x2a, 0x26, 0x71, 0x4c, 0x06, 0xcc, 0xe8, 0x54, 0x6e, 0x2e, 0xfe, 0xd3, 0x2c,
	0xc9, 0xb9, 0x9d, 0x62, 0xe8, 0x39, 0xf0, 0x25, 0x19, 0x30, 0xff, 0x8f, 0x55, 0x80, 0x8b, 0xae,
	0xd0, 0x27, 0x00, 0x8a, 0xc8, 0x3e, 0x53, 0x38, 0x93, 0x7c, 0x9a, 0x58, 0xb6, 0xd0, 0xf7, 0x92,
	0xa3, 0x01, 0xac, 0xd3, 0x33, 0x12, 0xc7, 0x2c, 0xc2, 0x54, 0xb2, 0x2e, 0x8b, 0x75, 0x35, 0xa9,
	0x53, 0xf1, 0xc9, 0x8d, 0x55, 0x0c, 0x5a, 0x36, 0x48, 0xeb, 0x22, 0x46, 0x88, 0xe8, 0x8c, 0x0d,
	0x75, 0xa1, 0x42, 0x49, 0x94, 0xcf, 0x35, 0x6f, 0x94, 0xda, 0xfb, 0x0f, 0xb9, 0x48, 0x94, 0x4b,
	0xb4, 0x4a, 0xf3, 0x06, 0xb4, 0x0b, 0x5e, 0xaa, 0x88, 0xc2, 0x89, 0x64, 0x3d, 0xfe, 0xbe, 0x56,
	0xca, 0x77, 0x0f, 0x1a, 0x3b, 0x31, 0x10, 0x7a, 0x0c, 0xb5, 0x89, 0x52, 0x70, 0x8f, 0x50, 0x25,
	0xe4, 0xc8, 0xaa, 0x7d, 0x47, 0xd3, 0xc2, 0x8d, 0x09, 0xfc, 0xa9, 0x85, 0xb5, 0xde, 0xa8, 0x0e,
	0x0b, 0x54, 0xc4, 0x3d, 0xde, 0xaf, 0x2d, 0x18, 0xad, 0x36, 0x67, 0xe6, 0xa4, 0x63, 0x2e, 0x53,
	0xe8, 0xdc, 0xfc, 0xdf, 0x8b, 0xb0, 0xd2, 0x49, 0x73, 0x75, 0x3e, 0x01, 0x90, 0x42, 0x28, 0x4c,
	0x99, 0x54, 0xa9, 0xbb, 0x05, 0x0f, 0x2e, 0xd1, 0xe1, 0x80, 0x28, 0xd2, 0x11, 0x99, 0xa4, 0x2c,
	0x2c, 0x6b, 0x42, 0x4b, 0xfb, 0xa3, 0xaf, 0xc1, 0x4b, 0x24, 0x1f, 0x12, 0xc5, 0xf0, 0x5b, 0x36,
	0x72, 0x47, 0x76, 0x0d, 0x1d, 0x1c, 0xe3, 0x3b, 0x36, 0xd2, 0xd9, 0x75, 0x62, 0x4c, 0xcf, 0x08,
	0x8f, 0xdd, 0xb4, 0x5f, 0x97, 0x5d, 0x13, 0x5a, 0xda, 0xdf, 0xaf, 0xc1, 0x86, 0x3d, 0x92, 0x63,
	0x41, 0xc9, 0x64, 0x57, 0xfe, 0x6f, 0x73, 0x80, 0x66, 0xc7, 0x01, 0x51, 0x58, 0x4d, 0xd3, 0xfc,
	0xc9, 0xdb, 0x8e, 0x1f, 0xdf, 0xfc, 0xe4, 0xf3, 0xfa, 0xb5, 0x0b, 0xe1, 0x4a, 0x9a, 0x57, 0xf4,
	0x1b, 0x58, 0x71, 0xcb, 0xa0, 0xcb, 0x7a, 0x24, 0x8b, 0x94, 0x93, 0x65, 0x63, 0xe6, 0x74, 0x0e,
	0xf5, 0x32, 0x6b, 0x17, 0xc2, 0xbb, 0x16, 0x38, 0xb0, 0xee, 0x48, 0xc0, 0x5a, 0xa4, 0x1b, 0x9a,
	0x9a, 0x50, 0x1d, 0xe3, 0xdb, 0x9b, 0xd7, 0x79, 0xb9, 0x32, 0xed, 0x42, 0x58, 0x89, 0xa6, 0x6c,
	0xcd, 0x7b, 0x50, 0xbd, 0x48, 0x85, 0xd3, 0x84, 0x51, 0xde, 0xe3, 0x4c, 0xa2, 0xf9, 0xbf, 0x9b,
	0x45, 0xff, 0xa7, 0x25, 0x58, 0x9d, 0x9a, 0x76, 0xf4, 0x11, 0x2c, 0x13, 0x4a, 0x59, 0x9a, 0x62,
	0x25, 0xde, 0xb2, 0xd8, 0xde, 0xed, 0x76, 0x21, 0xf4, 0xac, 0xf5, 0x95, 0x36, 0xa2, 0x63, 0xf8,
	0x9f, 0xd3, 0x81, 0x8a, 0x41, 0x92, 0x29, 0x86, 0x59, 0xdc, 0xe7, 0x31, 0xbb, 0x56, 0x8e, 0x75,
	0x0b, 0xb4, 0x2c, 0xeb, 0xd0, 0x90, 0x50, 0x03, 0xaa, 0x2e, 0x9a, 0x64, 0x3d, 0xc9, 0xd2, 0x33,
	0x97, 0x7a, 0xde, 0xa5, 0x46, 0x16, 0x0d, 0x2d, 0x68, 0x2b, 0xf8, 0xb9, 0x08, 0xbe, 0x7b, 0xd9,
	0x30, 0xa1, 0x54, 0x64, 0xb1, 0xc2, 0x6f, 0xde, 0x29, 0x6c, 0xab, 0x34, 0x77, 0xd2, 0x6b, 0xfc,
	0x78, 0xeb, 0x4b, 0x1f, 0x38, 0x97, 0x7d, 0x1b, 0xfa, 0xf9, 0xeb, 0x57, 0xfb, 0x26, 0x70, 0x5e,
	0xee, 0xcd, 0x34, 0xef, 0xf5, 0x4e, 0x59, 0x2f, 0x24, 0xc0, 0x2d, 0x7d, 0xcc, 0xc9, 0xc0, 0xdc,
	0x74, 0xaf, 0xf1, 0xf2, 0xf6, 0xc5, 0x58, 0xe8, 0x68, 0xff, 0x45, 0x3e, 0x7d, 0xd9, 0xe6, 0x38,
	0x22, 0x03, 0xf4, 0x01, 0xbc, 0x9e, 0x14, 0x03, 0x9c, 0x44, 0x59, 0x9f, 0xc7, 0x6e, 0x67, 0xbc,
	0xbe, 0x7d, 0xc6, 0xf1, 0x83, 0x31, 0x61, 0x7b, 0x2a, 0xc5, 0xe0, 0xc4, 0x84, 0xd7, 0x6f, 0x5a,
	0xef, 0xfc, 0xcf, 0xcf, 0xe0, 0xe1, 0xf5, 0x6a, 0xa1, 0x2d, 0x58, 0x7a, 0x93, 0x8a, 0xd8, 0xec,
	0x12, 0x33, 0x53, 0xe1, 0xa2, 0xfe, 0xd7, 0x9b, 0xe2, 0x4b, 0xd8, 0x30, 0x07, 0x8e, 0x23, 0xde,
	0x63, 0xfa, 0xd1, 0xc3, 0x29, 0xa3, 0x22, 0xee, 0xda, 0x77, 0xa2, 0x14, 0x56, 0x0d, 0x7a, 0xec,
	0xc0, 0x8e, 0xc5, 0xfc, 0x21, 0x54, 0x2f, 0xd3, 0x05, 0xd5, 0x61, 0x9d, 0x64, 0xea, 0x4c, 0x48,
	0xfe, 0xc1, 0xbc, 0xa3, 0x93, 0x73, 0x1c, 0xa2, 0x1c, 0x64, 0x47, 0xe9, 0x73, 0x18, 0x5b, 0xd5,
	0x08, 0xa7, 0x2c, 0x62, 0x7a, 0x0b, 0x9b, 0xd4, 0xe5, 0x70, 0xed, 0x1c, 0xe9, 0x38, 0xc0, 0xff,
	0xb5, 0x08, 0x0f, 0xae, 0x94, 0x07, 0x21, 0x28, 0x5d, 0xbc, 0xa7, 0xa1, 0xf9, 0x46, 0x5f, 0x9c,
	0xef, 0xf3, 0xb9, 0x2b, 0xf7, 0x79, 0xbb, 0x30, 0xde, 0xe8, 0x68, 0x0f, 0x96, 0xd5, 0x28, 0x61,
	0x5d, 0xec, 0x88, 0x76, 0x4d, 0x54, 0x67, 0x88, 0xfb, 0xb1, 0xbe, 0x59, 0x9e, 0xf1, 0x6d, 0x19,
	0xd7, 0xe6, 0x5d, 0xf0, 0x2c, 0x09, 0x6b, 0xeb, 0x95, 0x4b, 0xa0, 0xb9, 0x09, 0x15, 0xf7, 0x94,
	0xe7, 0x81, 0xe7, 0xa5, 0xa5, 0x52, 0xe5, 0x4e, 0x73, 0xef, 0x97, 0xbf, 0xb6, 0x8b, 0xf0, 0x7f,
	0x2e, 0xec, 0x30, 0x25, 0x52, 0xbc, 0x1f, 0xcd, 0xce, 0x55, 0xb3, 0x32, 0x31, 0x58, 0x27, 0xba,
	0xb2, 0x93, 0xe2, 0xe9, 0x82, 0x29, 0xf1, 0xd1, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x4a,
	0x5e, 0x86, 0x9a, 0x0a, 0x00, 0x00,
}
