// Code generated by protoc-gen-go. DO NOT EDIT.
// source: envoy/api/v2/core/protocol.proto

package core

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import types "github.com/gogo/protobuf/types"
import _ "github.com/lyft/protoc-gen-validate/validate"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// [#not-implemented-hide:]
type TcpProtocolOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TcpProtocolOptions) Reset()         { *m = TcpProtocolOptions{} }
func (m *TcpProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*TcpProtocolOptions) ProtoMessage()    {}
func (*TcpProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_97d21855118f0124, []int{0}
}
func (m *TcpProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcpProtocolOptions.Unmarshal(m, b)
}
func (m *TcpProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcpProtocolOptions.Marshal(b, m, deterministic)
}
func (dst *TcpProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcpProtocolOptions.Merge(dst, src)
}
func (m *TcpProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_TcpProtocolOptions.Size(m)
}
func (m *TcpProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_TcpProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_TcpProtocolOptions proto.InternalMessageInfo

type HttpProtocolOptions struct {
	// The idle timeout for upstream connection pool connections. The idle timeout is defined as the
	// period in which there are no active requests. If not set, there is no idle timeout. When the
	// idle timeout is reached the connection will be closed. Note that request based timeouts mean
	// that HTTP/2 PINGs will not keep the connection alive.
	IdleTimeout          *types.Duration `protobuf:"bytes,1,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HttpProtocolOptions) Reset()         { *m = HttpProtocolOptions{} }
func (m *HttpProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*HttpProtocolOptions) ProtoMessage()    {}
func (*HttpProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_97d21855118f0124, []int{1}
}
func (m *HttpProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpProtocolOptions.Unmarshal(m, b)
}
func (m *HttpProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpProtocolOptions.Marshal(b, m, deterministic)
}
func (dst *HttpProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpProtocolOptions.Merge(dst, src)
}
func (m *HttpProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_HttpProtocolOptions.Size(m)
}
func (m *HttpProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_HttpProtocolOptions proto.InternalMessageInfo

func (m *HttpProtocolOptions) GetIdleTimeout() *types.Duration {
	if m != nil {
		return m.IdleTimeout
	}
	return nil
}

type Http1ProtocolOptions struct {
	// Handle HTTP requests with absolute URLs in the requests. These requests
	// are generally sent by clients to forward/explicit proxies. This allows clients to configure
	// envoy as their HTTP proxy. In Unix, for example, this is typically done by setting the
	// *http_proxy* environment variable.
	AllowAbsoluteUrl *types.BoolValue `protobuf:"bytes,1,opt,name=allow_absolute_url,json=allowAbsoluteUrl,proto3" json:"allow_absolute_url,omitempty"`
	// Handle incoming HTTP/1.0 and HTTP 0.9 requests.
	// This is off by default, and not fully standards compliant. There is support for pre-HTTP/1.1
	// style connect logic, dechunking, and handling lack of client host iff
	// *default_host_for_http_10* is configured.
	AcceptHttp_10 bool `protobuf:"varint,2,opt,name=accept_http_10,json=acceptHttp10,proto3" json:"accept_http_10,omitempty"`
	// A default host for HTTP/1.0 requests. This is highly suggested if *accept_http_10* is true as
	// Envoy does not otherwise support HTTP/1.0 without a Host header.
	// This is a no-op if *accept_http_10* is not true.
	DefaultHostForHttp_10 string   `protobuf:"bytes,3,opt,name=default_host_for_http_10,json=defaultHostForHttp10,proto3" json:"default_host_for_http_10,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Http1ProtocolOptions) Reset()         { *m = Http1ProtocolOptions{} }
func (m *Http1ProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*Http1ProtocolOptions) ProtoMessage()    {}
func (*Http1ProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_97d21855118f0124, []int{2}
}
func (m *Http1ProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http1ProtocolOptions.Unmarshal(m, b)
}
func (m *Http1ProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http1ProtocolOptions.Marshal(b, m, deterministic)
}
func (dst *Http1ProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http1ProtocolOptions.Merge(dst, src)
}
func (m *Http1ProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_Http1ProtocolOptions.Size(m)
}
func (m *Http1ProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Http1ProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Http1ProtocolOptions proto.InternalMessageInfo

func (m *Http1ProtocolOptions) GetAllowAbsoluteUrl() *types.BoolValue {
	if m != nil {
		return m.AllowAbsoluteUrl
	}
	return nil
}

func (m *Http1ProtocolOptions) GetAcceptHttp_10() bool {
	if m != nil {
		return m.AcceptHttp_10
	}
	return false
}

func (m *Http1ProtocolOptions) GetDefaultHostForHttp_10() string {
	if m != nil {
		return m.DefaultHostForHttp_10
	}
	return ""
}

type Http2ProtocolOptions struct {
	// `Maximum table size <http://httpwg.org/specs/rfc7541.html#rfc.section.4.2>`_
	// (in octets) that the encoder is permitted to use for the dynamic HPACK table. Valid values
	// range from 0 to 4294967295 (2^32 - 1) and defaults to 4096. 0 effectively disables header
	// compression.
	HpackTableSize *types.UInt32Value `protobuf:"bytes,1,opt,name=hpack_table_size,json=hpackTableSize,proto3" json:"hpack_table_size,omitempty"`
	// `Maximum concurrent streams <http://httpwg.org/specs/rfc7540.html#rfc.section.5.1.2>`_
	// allowed for peer on one HTTP/2 connection. Valid values range from 1 to 2147483647 (2^31 - 1)
	// and defaults to 2147483647.
	MaxConcurrentStreams *types.UInt32Value `protobuf:"bytes,2,opt,name=max_concurrent_streams,json=maxConcurrentStreams,proto3" json:"max_concurrent_streams,omitempty"`
	// This field also acts as a soft limit on the number of bytes Envoy will buffer per-stream in the
	// HTTP/2 codec buffers. Once the buffer reaches this pointer, watermark callbacks will fire to
	// stop the flow of data to the codec buffers.
	InitialStreamWindowSize *types.UInt32Value `protobuf:"bytes,3,opt,name=initial_stream_window_size,json=initialStreamWindowSize,proto3" json:"initial_stream_window_size,omitempty"`
	// Similar to *initial_stream_window_size*, but for connection-level flow-control
	// window. Currently, this has the same minimum/maximum/default as *initial_stream_window_size*.
	InitialConnectionWindowSize *types.UInt32Value `protobuf:"bytes,4,opt,name=initial_connection_window_size,json=initialConnectionWindowSize,proto3" json:"initial_connection_window_size,omitempty"`
	// Allows proxying Websocket and other upgrades over H2 connect.
	AllowConnect bool `protobuf:"varint,5,opt,name=allow_connect,json=allowConnect,proto3" json:"allow_connect,omitempty"`
	// [#not-implemented-hide:] Hiding until envoy has full metadata support.
	// Still under implementation. DO NOT USE.
	//
	// Allows metadata. See [metadata
	// docs](https://github.com/envoyproxy/envoy/blob/master/source/docs/h2_metadata.md) for more
	// information.
	AllowMetadata        bool     `protobuf:"varint,6,opt,name=allow_metadata,json=allowMetadata,proto3" json:"allow_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http2ProtocolOptions) Reset()         { *m = Http2ProtocolOptions{} }
func (m *Http2ProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*Http2ProtocolOptions) ProtoMessage()    {}
func (*Http2ProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_97d21855118f0124, []int{3}
}
func (m *Http2ProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http2ProtocolOptions.Unmarshal(m, b)
}
func (m *Http2ProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http2ProtocolOptions.Marshal(b, m, deterministic)
}
func (dst *Http2ProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http2ProtocolOptions.Merge(dst, src)
}
func (m *Http2ProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_Http2ProtocolOptions.Size(m)
}
func (m *Http2ProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_Http2ProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_Http2ProtocolOptions proto.InternalMessageInfo

func (m *Http2ProtocolOptions) GetHpackTableSize() *types.UInt32Value {
	if m != nil {
		return m.HpackTableSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetMaxConcurrentStreams() *types.UInt32Value {
	if m != nil {
		return m.MaxConcurrentStreams
	}
	return nil
}

func (m *Http2ProtocolOptions) GetInitialStreamWindowSize() *types.UInt32Value {
	if m != nil {
		return m.InitialStreamWindowSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetInitialConnectionWindowSize() *types.UInt32Value {
	if m != nil {
		return m.InitialConnectionWindowSize
	}
	return nil
}

func (m *Http2ProtocolOptions) GetAllowConnect() bool {
	if m != nil {
		return m.AllowConnect
	}
	return false
}

func (m *Http2ProtocolOptions) GetAllowMetadata() bool {
	if m != nil {
		return m.AllowMetadata
	}
	return false
}

// [#not-implemented-hide:]
type GrpcProtocolOptions struct {
	Http2ProtocolOptions *Http2ProtocolOptions `protobuf:"bytes,1,opt,name=http2_protocol_options,json=http2ProtocolOptions,proto3" json:"http2_protocol_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GrpcProtocolOptions) Reset()         { *m = GrpcProtocolOptions{} }
func (m *GrpcProtocolOptions) String() string { return proto.CompactTextString(m) }
func (*GrpcProtocolOptions) ProtoMessage()    {}
func (*GrpcProtocolOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_97d21855118f0124, []int{4}
}
func (m *GrpcProtocolOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcProtocolOptions.Unmarshal(m, b)
}
func (m *GrpcProtocolOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcProtocolOptions.Marshal(b, m, deterministic)
}
func (dst *GrpcProtocolOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcProtocolOptions.Merge(dst, src)
}
func (m *GrpcProtocolOptions) XXX_Size() int {
	return xxx_messageInfo_GrpcProtocolOptions.Size(m)
}
func (m *GrpcProtocolOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcProtocolOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcProtocolOptions proto.InternalMessageInfo

func (m *GrpcProtocolOptions) GetHttp2ProtocolOptions() *Http2ProtocolOptions {
	if m != nil {
		return m.Http2ProtocolOptions
	}
	return nil
}

func init() {
	proto.RegisterType((*TcpProtocolOptions)(nil), "envoy.api.v2.core.TcpProtocolOptions")
	proto.RegisterType((*HttpProtocolOptions)(nil), "envoy.api.v2.core.HttpProtocolOptions")
	proto.RegisterType((*Http1ProtocolOptions)(nil), "envoy.api.v2.core.Http1ProtocolOptions")
	proto.RegisterType((*Http2ProtocolOptions)(nil), "envoy.api.v2.core.Http2ProtocolOptions")
	proto.RegisterType((*GrpcProtocolOptions)(nil), "envoy.api.v2.core.GrpcProtocolOptions")
}

func init() {
	proto.RegisterFile("envoy/api/v2/core/protocol.proto", fileDescriptor_protocol_97d21855118f0124)
}

var fileDescriptor_protocol_97d21855118f0124 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0xe5, 0x2f, 0xfd, 0x4a, 0xd9, 0x96, 0xd2, 0xba, 0x56, 0x6b, 0x0a, 0x2a, 0x51, 0x00,
	0x11, 0xf5, 0x60, 0xb7, 0xae, 0xc4, 0x9d, 0x14, 0x95, 0x72, 0x40, 0x20, 0x37, 0x05, 0x71, 0x40,
	0xab, 0xcd, 0x7a, 0x93, 0xac, 0xd8, 0x78, 0xac, 0xf5, 0x38, 0x29, 0x7d, 0x12, 0x1e, 0x81, 0x67,
	0xe0, 0x80, 0x78, 0x13, 0x24, 0x6e, 0x9c, 0x79, 0x00, 0x23, 0x7b, 0x37, 0x11, 0x24, 0x95, 0x40,
	0xdc, 0x46, 0x33, 0xf3, 0xff, 0xff, 0x66, 0xec, 0x59, 0xd2, 0x14, 0xe9, 0x18, 0xde, 0x87, 0x2c,
	0x93, 0xe1, 0x38, 0x0a, 0x39, 0x68, 0x11, 0x66, 0x1a, 0x10, 0x38, 0xa8, 0xa0, 0x0e, 0xdc, 0xcd,
	0xba, 0x23, 0x60, 0x99, 0x0c, 0xc6, 0x51, 0x50, 0x75, 0xec, 0xee, 0x0d, 0x00, 0x06, 0xca, 0x76,
	0xf6, 0x8a, 0x7e, 0x98, 0x14, 0x9a, 0xa1, 0x84, 0xd4, 0x48, 0x16, 0xeb, 0x13, 0xcd, 0xb2, 0x4c,
	0xe8, 0xdc, 0xd6, 0x77, 0xc6, 0x4c, 0xc9, 0x84, 0xa1, 0x08, 0xa7, 0x81, 0x2d, 0x78, 0x03, 0x18,
	0x40, 0x1d, 0x86, 0x55, 0x64, 0xb2, 0x2d, 0x8f, 0xb8, 0x5d, 0x9e, 0xbd, 0xb4, 0x63, 0xbd, 0xc8,
	0x2a, 0x52, 0xde, 0x7a, 0x43, 0xb6, 0x4e, 0x11, 0xe7, 0xd3, 0x6e, 0x87, 0xac, 0xc9, 0x44, 0x09,
	0x8a, 0x72, 0x24, 0xa0, 0x40, 0xdf, 0x69, 0x3a, 0xed, 0xd5, 0xe8, 0x56, 0x60, 0x46, 0x0a, 0xa6,
	0x23, 0x05, 0x4f, 0xec, 0xc8, 0x9d, 0xa5, 0x0f, 0x5f, 0xef, 0x3a, 0xf1, 0x6a, 0x25, 0xea, 0x1a,
	0x4d, 0xeb, 0xb3, 0x43, 0xbc, 0xca, 0xfb, 0x70, 0xde, 0xfc, 0x94, 0xb8, 0x4c, 0x29, 0x98, 0x50,
	0xd6, 0xcb, 0x41, 0x15, 0x28, 0x68, 0xa1, 0x95, 0x45, 0xec, 0x2e, 0x20, 0x3a, 0x00, 0xea, 0x15,
	0x53, 0x85, 0x88, 0x37, 0x6a, 0xd5, 0x63, 0x2b, 0x3a, 0xd7, 0xca, 0xbd, 0x4f, 0xd6, 0x19, 0xe7,
	0x22, 0x43, 0x3a, 0x44, 0xcc, 0xe8, 0xe1, 0x81, 0xff, 0x5f, 0xd3, 0x69, 0xaf, 0xc4, 0x6b, 0x26,
	0x5b, 0xd3, 0x0f, 0xdc, 0x47, 0xc4, 0x4f, 0x44, 0x9f, 0x15, 0x0a, 0xe9, 0x10, 0x72, 0xa4, 0x7d,
	0xd0, 0xb3, 0xfe, 0x46, 0xd3, 0x69, 0x5f, 0x8f, 0x3d, 0x5b, 0x3f, 0x85, 0x1c, 0x4f, 0x40, 0x1b,
	0x5d, 0xeb, 0x47, 0xc3, 0x2c, 0x10, 0xcd, 0x2f, 0x70, 0x42, 0x36, 0x86, 0x19, 0xe3, 0xef, 0x28,
	0xb2, 0x9e, 0x12, 0x34, 0x97, 0x97, 0xc2, 0x8e, 0x7f, 0x67, 0x61, 0xfc, 0xf3, 0x67, 0x29, 0x1e,
	0x45, 0x66, 0x81, 0xf5, 0x5a, 0xd5, 0xad, 0x44, 0x67, 0xf2, 0x52, 0xb8, 0x9c, 0x6c, 0x8f, 0xd8,
	0x05, 0xe5, 0x90, 0xf2, 0x42, 0x6b, 0x91, 0x22, 0xcd, 0x51, 0x0b, 0x36, 0xca, 0xeb, 0x35, 0xfe,
	0xe0, 0xd6, 0xb9, 0xf9, 0xe9, 0xfb, 0x97, 0x06, 0xd9, 0x5f, 0xf1, 0xcb, 0xb2, 0x2c, 0xaf, 0xb5,
	0x9d, 0xd8, 0x1b, 0xb1, 0x8b, 0xe3, 0x99, 0xd7, 0x99, 0xb1, 0x72, 0x15, 0xd9, 0x95, 0xa9, 0x44,
	0xc9, 0x94, 0x75, 0xa7, 0x13, 0x99, 0x26, 0x30, 0x31, 0x63, 0x37, 0xfe, 0x02, 0xb4, 0x59, 0x81,
	0xd6, 0xf6, 0x89, 0x05, 0x95, 0x65, 0x23, 0xde, 0xb1, 0x96, 0x06, 0xf2, 0xba, 0x36, 0xac, 0x57,
	0x42, 0xb2, 0x37, 0xa5, 0x71, 0x48, 0x53, 0xc1, 0xab, 0x2f, 0xf6, 0x1b, 0x71, 0xe9, 0xdf, 0x88,
	0xb7, 0xad, 0xed, 0xf1, 0xcc, 0xf5, 0x17, 0xea, 0x3d, 0x72, 0xc3, 0x5c, 0x94, 0x65, 0xfa, 0xff,
	0xdb, 0x33, 0xa8, 0x92, 0x56, 0xe1, 0x3e, 0x20, 0xeb, 0xa6, 0x69, 0x24, 0x90, 0x25, 0x0c, 0x99,
	0xbf, 0x5c, 0x77, 0x19, 0xe9, 0x73, 0x9b, 0x6c, 0x21, 0xd9, 0x7a, 0xaa, 0x33, 0x3e, 0xff, 0xcf,
	0xdf, 0x92, 0xed, 0xea, 0x66, 0x22, 0x3a, 0x7d, 0xd8, 0x14, 0x4c, 0xc5, 0xfe, 0xf9, 0x87, 0xc1,
	0xc2, 0x0b, 0x0f, 0xae, 0x3a, 0x9e, 0xd8, 0x1b, 0x5e, 0x91, 0xed, 0x2c, 0x7d, 0xfc, 0xb6, 0xe7,
	0xf4, 0x96, 0x6b, 0xf3, 0xa3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x28, 0x0e, 0x73, 0x0a, 0x50,
	0x04, 0x00, 0x00,
}
